/* eslint-disable n8n-nodes-base/node-param-option-name-wrong-for-upsert, n8n-nodes-base/node-param-description-wrong-for-upsert, n8n-nodes-base/node-param-display-name-wrong-for-dynamic-options, n8n-nodes-base/node-param-description-wrong-for-dynamic-options, n8n-nodes-base/node-param-description-wrong-for-return-all, n8n-nodes-base/node-param-description-wrong-for-limit, n8n-nodes-base/node-param-description-boolean-without-whether, n8n-nodes-base/node-param-display-name-miscased, n8n-nodes-base/node-param-placeholder-miscased-id -- A interface deste nó privado é deliberadamente localizada em português. */
import type { INodeProperties } from 'n8n-workflow';

const operation = (
	resource: string,
	options: Array<{ name: string; value: string; action: string; description: string }>,
	defaultValue: string,
): INodeProperties => ({
	displayName: 'Operação',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: [resource] } },
	options,
	default: defaultValue,
});

const crudOperations = (noun: string, includeUpsert = false) => [
	{ name: 'Criar', value: 'create', action: `Criar ${noun}`, description: `Cria ${noun}` },
	{ name: 'Obter', value: 'get', action: `Obter ${noun}`, description: `Obtém ${noun} por ID` },
	{
		name: 'Obter Muitos',
		value: 'getMany',
		action: `Obter muitos ${noun}`,
		description: `Lista ${noun}`,
	},
	{
		name: 'Pesquisar',
		value: 'search',
		action: `Pesquisar ${noun}`,
		description: `Pesquisa ${noun} por texto`,
	},
	{
		name: 'Atualizar',
		value: 'update',
		action: `Atualizar ${noun}`,
		description: `Atualiza ${noun}`,
	},
	...(includeUpsert
		? [
				{
					name: 'Criar ou Atualizar',
					value: 'upsert',
					action: `Criar ou atualizar ${noun}`,
					description: 'Cria um registro ou atualiza o correspondente existente (upsert)',
				},
			]
		: []),
];

const listOperations = ['getMany', 'search'];
const bodyOperations = ['create', 'update', 'upsert'];

export const tavioCrmProperties: INodeProperties[] = [
	{
		displayName: 'Recurso',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Atividade', value: 'activity' },
			{ name: 'Contato', value: 'contact' },
			{ name: 'Empresa', value: 'organization' },
			{ name: 'Funil', value: 'pipeline' },
			{ name: 'Lead', value: 'lead' },
			{ name: 'Negócio', value: 'deal' },
			{ name: 'Nota', value: 'note' },
			{ name: 'Produto', value: 'product' },
			{ name: 'Requisição Avançada', value: 'advanced' },
			{ name: 'Tag', value: 'tag' },
		],
		default: 'contact',
	},
	operation('contact', crudOperations('um contato', true), 'create'),
	operation('organization', crudOperations('uma empresa', true), 'create'),
	operation(
		'lead',
		[
			...crudOperations('um lead'),
			{
				name: 'Arquivar',
				value: 'archive',
				action: 'Arquivar um lead',
				description: 'Arquiva um lead',
			},
			{
				name: 'Converter',
				value: 'convert',
				action: 'Converter um lead',
				description: 'Converte o lead em negócio',
			},
		],
		'create',
	),
	operation(
		'deal',
		[
			...crudOperations('um negócio'),
			{
				name: 'Adicionar Produto',
				value: 'addProduct',
				action: 'Adicionar produto ao negócio',
				description: 'Adiciona um item de produto',
			},
			{
				name: 'Marcar Como Ganho',
				value: 'won',
				action: 'Marcar negócio como ganho',
				description: 'Fecha como ganho',
			},
			{
				name: 'Marcar Como Perdido',
				value: 'lost',
				action: 'Marcar negócio como perdido',
				description: 'Fecha como perdido',
			},
			{
				name: 'Mover',
				value: 'move',
				action: 'Mover um negócio',
				description: 'Move para outra etapa',
			},
			{
				name: 'Reabrir',
				value: 'reopen',
				action: 'Reabrir um negócio',
				description: 'Reabre um negócio fechado',
			},
		],
		'create',
	),
	operation(
		'activity',
		[
			{
				name: 'Criar',
				value: 'create',
				action: 'Criar uma atividade',
				description: 'Cria uma atividade',
			},
			{ name: 'Obter', value: 'get', action: 'Obter uma atividade', description: 'Obtém por ID' },
			{
				name: 'Obter Muitas',
				value: 'getMany',
				action: 'Obter muitas atividades',
				description: 'Lista atividades',
			},
			{
				name: 'Atualizar',
				value: 'update',
				action: 'Atualizar uma atividade',
				description: 'Atualiza uma atividade',
			},
			{
				name: 'Concluir',
				value: 'complete',
				action: 'Concluir uma atividade',
				description: 'Marca como concluída',
			},
		],
		'create',
	),
	operation(
		'note',
		[
			{
				name: 'Criar',
				value: 'create',
				action: 'Criar uma nota',
				description: 'Cria nota vinculada',
			},
		],
		'create',
	),
	operation(
		'product',
		[
			{
				name: 'Criar',
				value: 'create',
				action: 'Criar um produto',
				description: 'Cria produto ou serviço',
			},
			{
				name: 'Obter Muitos',
				value: 'getMany',
				action: 'Obter muitos produtos',
				description: 'Lista produtos',
			},
			{
				name: 'Atualizar',
				value: 'update',
				action: 'Atualizar um produto',
				description: 'Atualiza produto ou serviço',
			},
		],
		'create',
	),
	operation(
		'pipeline',
		[
			{
				name: 'Obter Muitos',
				value: 'getMany',
				action: 'Obter muitos funis',
				description: 'Lista funis',
			},
			{
				name: 'Obter Etapas',
				value: 'getStages',
				action: 'Obter etapas do funil',
				description: 'Lista etapas de um funil',
			},
		],
		'getMany',
	),
	operation(
		'tag',
		[
			{
				name: 'Adicionar Ao Item',
				value: 'add',
				action: 'Adicionar tag ao item',
				description: 'Adiciona uma tag preservando as existentes',
			},
			{
				name: 'Obter Muitas',
				value: 'getMany',
				action: 'Obter muitas tags',
				description: 'Lista tags',
			},
			{
				name: 'Remover Do Item',
				value: 'remove',
				action: 'Remover tag do item',
				description: 'Remove uma tag preservando as demais',
			},
		],
		'getMany',
	),
	operation(
		'advanced',
		[
			{
				name: 'Executar',
				value: 'request',
				action: 'Executar requisição avançada',
				description: 'Executa requisição na mesma origem da credencial',
			},
		],
		'request',
	),
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact', 'organization', 'lead', 'deal', 'activity', 'product'],
				operation: [
					'get',
					'update',
					'archive',
					'convert',
					'move',
					'won',
					'lost',
					'reopen',
					'addProduct',
					'complete',
				],
			},
		},
		description: 'ID do registro no Tavio CRM',
	},
	{
		displayName: 'Campos (JSON)',
		name: 'fields',
		type: 'json',
		default: '{}',
		displayOptions: {
			show: {
				resource: ['contact', 'organization', 'lead', 'deal', 'activity', 'product'],
				operation: bodyOperations,
			},
		},
		description: 'Campos aceitos pela API; dinheiro deve ser enviado como string decimal',
	},
	{
		displayName: 'Campos Personalizados',
		name: 'customFields',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: {
			show: {
				resource: ['contact', 'organization', 'lead', 'deal', 'product'],
				operation: bodyOperations,
			},
		},
		options: [
			{
				name: 'values',
				displayName: 'Campo',
				values: [
					{
						displayName: 'Campo Nome ou ID',
						name: 'fieldId',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getCustomFields' },
						default: '',
						required: true,
						description: 'Escolha na lista ou informe um ID usando uma expressão',
					},
					{
						displayName: 'Valor (JSON)',
						name: 'value',
						type: 'string',
						default: '',
						description: 'Valor JSON ou texto simples do campo',
					},
				],
			},
		],
	},
	{
		displayName: 'Correspondência',
		name: 'upsertBy',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'E-Mail', value: 'email' },
			{ name: 'External ID', value: 'externalId' },
			{ name: 'Telefone', value: 'phone' },
		],
		default: 'email',
		displayOptions: { show: { resource: ['contact'], operation: ['upsert'] } },
	},
	{
		displayName: 'E-Mail Para Correspondência',
		name: 'matchEmail',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { resource: ['contact'], operation: ['upsert'], upsertBy: ['email'] },
		},
		description: 'E-mail normalizado usado para localizar um único contato',
	},
	{
		displayName: 'External ID',
		name: 'externalId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { resource: ['contact'], operation: ['upsert'], upsertBy: ['externalId'] },
		},
		description: 'Identificador estável do contato no sistema de origem',
	},
	{
		displayName: 'Telefone Para Correspondência',
		name: 'matchPhone',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { resource: ['contact'], operation: ['upsert'], upsertBy: ['phone'] },
		},
		description: 'Telefone normalizado usado para localizar um único contato',
	},
	{
		displayName: 'Versão',
		name: 'version',
		type: 'number',
		default: 1,
		required: true,
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: {
				resource: ['contact', 'organization', 'lead', 'deal'],
				operation: ['update', 'archive', 'convert', 'move', 'won', 'lost', 'reopen'],
			},
		},
		description: 'Versão otimista retornada pela API',
	},
	{
		displayName: 'Atualizado Em',
		name: 'updatedAt',
		type: 'dateTime',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['activity', 'product'], operation: ['update'] } },
		description: 'Valor updatedAt retornado pela leitura mais recente',
	},
	{
		displayName: 'Funil Nome ou ID',
		name: 'pipelineId',
		type: 'options',
		description: 'Escolha na lista ou informe um ID usando uma expressão',
		typeOptions: { loadOptionsMethod: 'getPipelines' },
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['deal', 'lead', 'pipeline'],
				operation: ['create', 'convert', 'getStages'],
			},
		},
	},
	{
		displayName: 'Etapa Nome ou ID',
		name: 'stageId',
		type: 'options',
		description: 'Escolha na lista ou informe um ID usando uma expressão',
		typeOptions: { loadOptionsMethod: 'getStages' },
		default: '',
		required: true,
		displayOptions: {
			show: { resource: ['deal', 'lead'], operation: ['create', 'convert', 'move'] },
		},
	},
	{
		displayName: 'Responsável Nome ou ID',
		name: 'ownerId',
		type: 'options',
		description: 'Escolha na lista ou informe um ID usando uma expressão',
		typeOptions: { loadOptionsMethod: 'getUsers' },
		default: '',
		displayOptions: {
			show: {
				resource: ['contact', 'organization', 'lead', 'deal', 'activity'],
				operation: bodyOperations,
			},
		},
	},
	{
		displayName: 'Equipe Nome ou ID',
		name: 'teamId',
		type: 'options',
		description: 'Escolha na lista ou informe um ID usando uma expressão',
		typeOptions: { loadOptionsMethod: 'getTeams' },
		default: '',
		displayOptions: {
			show: {
				resource: ['contact', 'organization', 'lead', 'deal', 'activity'],
				operation: bodyOperations,
			},
		},
	},
	{
		displayName: 'Produto Nome ou ID',
		name: 'productId',
		type: 'options',
		description: 'Escolha na lista ou informe um ID usando uma expressão',
		typeOptions: { loadOptionsMethod: 'getProducts' },
		default: '',
		displayOptions: { show: { resource: ['deal'], operation: ['addProduct'] } },
	},
	{
		displayName: 'Item Do Negócio (JSON)',
		name: 'dealItem',
		type: 'json',
		default: '{"description":"","quantity":"1","unitPrice":"0.00"}',
		displayOptions: { show: { resource: ['deal'], operation: ['addProduct'] } },
	},
	{
		displayName: 'Motivo Da Perda',
		name: 'lostReason',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['deal'], operation: ['lost'] } },
	},
	{
		displayName: 'Resultado',
		name: 'result',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['activity'], operation: ['complete'] } },
	},
	{
		displayName: 'Tipo De Item',
		name: 'entityType',
		type: 'options',
		options: [
			{ name: 'Contato', value: 'contact' },
			{ name: 'Empresa', value: 'organization' },
			{ name: 'Lead', value: 'lead' },
			{ name: 'Negócio', value: 'deal' },
		],
		default: 'contact',
		displayOptions: { show: { resource: ['note'], operation: ['create'] } },
	},
	{
		displayName: 'Tipo De Item',
		name: 'entityType',
		type: 'options',
		options: [
			{ name: 'Contato', value: 'contact' },
			{ name: 'Empresa', value: 'organization' },
			{ name: 'Lead', value: 'lead' },
			{ name: 'Negócio', value: 'deal' },
			{ name: 'Produto', value: 'product' },
		],
		default: 'contact',
		displayOptions: { show: { resource: ['tag'], operation: ['add', 'remove'] } },
	},
	{
		displayName: 'ID Do Item',
		name: 'entityId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['note', 'tag'], operation: ['create', 'add', 'remove'] } },
	},
	{
		displayName: 'Conteúdo',
		name: 'content',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		displayOptions: { show: { resource: ['note'], operation: ['create'] } },
	},
	{
		displayName: 'Tag Nome ou ID',
		name: 'tagId',
		type: 'options',
		description: 'Escolha na lista ou informe um ID usando uma expressão',
		typeOptions: { loadOptionsMethod: 'getTags' },
		default: '',
		required: true,
		displayOptions: { show: { resource: ['tag'], operation: ['add', 'remove'] } },
	},
	{
		displayName: 'Pesquisar',
		name: 'search',
		type: 'string',
		default: '',
		displayOptions: { show: { operation: listOperations } },
	},
	{
		displayName: 'Retornar Tudo',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { operation: listOperations } },
		description: 'Se ativo, percorre automaticamente todas as páginas',
	},
	{
		displayName: 'Limite',
		name: 'limit',
		type: 'number',
		description: 'Número máximo de resultados a retornar',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 10000 },
		displayOptions: { show: { operation: listOperations, returnAll: [false] } },
	},
	{
		displayName: 'Chave De Idempotência',
		name: 'idempotencyKey',
		type: 'string',
		default: '',
		placeholder: '={{$execution.id + "-" + $itemIndex}}',
		description: 'Reutilize a mesma chave (8–200 caracteres) ao repetir uma mutação',
		displayOptions: { hide: { operation: ['get', 'getMany', 'search', 'getStages'] } },
	},
	{
		displayName: 'Simplificar Saída',
		name: 'simplifyOutput',
		type: 'boolean',
		default: true,
		description: 'Se desativado, retorna o envelope bruto da API',
	},
	{
		displayName: 'Método',
		name: 'method',
		type: 'options',
		options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map((value) => ({ name: value, value })),
		default: 'GET',
		displayOptions: { show: { resource: ['advanced'], operation: ['request'] } },
	},
	{
		displayName: 'Caminho',
		name: 'path',
		type: 'string',
		default: '/',
		required: true,
		description: 'Caminho relativo na mesma origem, por exemplo /contacts',
		displayOptions: { show: { resource: ['advanced'], operation: ['request'] } },
	},
	{
		displayName: 'Query (JSON)',
		name: 'query',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['advanced'], operation: ['request'] } },
	},
	{
		displayName: 'Corpo (JSON)',
		name: 'body',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['advanced'], operation: ['request'] } },
	},
];
